### ISSUE TITLE
Launchbox refused to open

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [AtomFry/LaunchBoxRomPatchManager#3]
I was getting warned that windows was refusing to allow this and to check properties yet saw nothing that was hindering the .dll So Launchbox refused to open with it being in the plugin folder!

**Comment by AtomFry** [comment]
Sometimes windows can block zip files or DLLs. You can right click the zip file you download and choose properties and see if it has an unblock check box at the bottom. I think the same issue can happen on the DLL files that get copied in the plugin folder. See if they are blocked by windows and if you can unblock them.

**Comment by AngryScotsmanGaming** [comment]
extracting them was fine, I shall check windows to see if I can somehow create an exception but never had issues with the previous release.... Thanks for getting back to me!

**Comment by AngryScotsmanGaming** [comment]
I didn't see that option but I got rid of the old files and put the new ones in there place all seems well now! thanks again for all your help and good work!

**Comment by AtomFry** [comment]
Nice, enjoy!
